version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd lambda/s3-event-notification
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package -DskipTests
artifacts:
  files:
    - lambda/s3-event-notification/target/s3-triggered-lambda.jar
  discard-paths: yes
